### PR TITLE
Interface naming

### PR DESCRIPTION
**Pull request by skyellin**

### CODE REVIEW

**Comment by hmoragregaCMP** [comment]
I'll accept adding redis as suggestion gladly, but not the interface naming, as PSR-1 and PSR-2 don't say anything about it, the naming convention is from Symfony CS

**Comment by skyellin** [comment]
It's part of FIG's "bylaws" http://www.php-fig.org/bylaws/psr-naming-conventions/

Also noted in Symfony's coding standards page under "Naming Conventions": http://symfony.com/doc/current/contributing/code/standards.html

**Comment by hmoragregaCMP** [comment]
But those laws apply for `Psr` packages (as stated in `5. The vendor namespace MUST be Psr`), not recommended coding style standards (PSR-1 & 2)

**Comment by skyellin** [comment]
Ok, but it's in the Symfony coding standards as well.  I thought that was what we were following. No?

**Pull request closed without merging**
